name: CI

on: [pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npx nx format:check --all

      - name: Lint code
        run:
          # TODO: npx nx affected:lint
          npx nx run-many --target=lint --all --parallel

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run:
          # TODO: npx nx affected:build
          npx nx run-many --target=build --all --parallel

      - name: Save artifacts for deployment
        if: ${{ matrix.node-version == '20.x' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/apps/wallet-react/exported

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run:
          # TODO: npx nx affected:test
          npx nx run-many --target=test --all --parallel

      - name: Test (e2e)
        run:
          # TODO: npx nx affected:e2e
          npx nx run-many --target=e2e --all --parallel
