name: CI

on:
  push: null
  pull_request:
    branches: ['main']

jobs:
  style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check style
        run: npx prettier --check "**/*.{js,ts,jsx,tsx,css,scss,json,yml,yaml}"

      - name: Lint code
        run:
          # TODO: npx nx affected:lint --base=main
          npx nx run-many --target=lint --all --parallel

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run:
          # TODO: npx nx affected:build --base=main
          npx nx run-many --target=build --all --parallel

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run:
          # TODO: npx nx affected:test --base=main
          npx nx run-many --target=test --all --parallel

  e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test (e2e)
        run:
          # TODO: npx nx affected:e2e --base=main
          npx nx run-many --target=e2e --all --parallel
